In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,7,'Harsh',34.23,True]

In [12]:
a1 = np.array(l1)

In [13]:
a2 = np.array([[1,2,3],[4,5,6]])

In [14]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
a1.ndim

1

In [16]:
a2.ndim

2

In [17]:
a3.ndim

3

In [18]:
 a1.size

7

In [19]:
a2.size

6

In [20]:
a3.size

9

In [21]:
a1.shape

(7,)

In [22]:
a2.shape

(2, 3)

In [23]:
a3.shape

(1, 3, 3)

In [41]:
np.random.randint(2,50,(3,4))

array([[29, 12, 18, 30],
       [32, 49, 16,  4],
       [33, 47, 46, 32]])

In [42]:
np.random.randint(2,50,(2,3,4))

array([[[ 5, 20, 29, 35],
        [38,  9,  5, 31],
        [23, 11, 16, 42]],

       [[33, 45,  5, 28],
        [31, 33,  8,  6],
        [31, 36, 42, 34]]])

In [44]:
np.random.rand(2,3)

array([[0.23071878, 0.31250147, 0.21210511],
       [0.53648569, 0.4036046 , 0.63686141]])

In [51]:
a4 = np.random.randn(4,4)

In [53]:
a4.reshape(4,2,2)

array([[[ 0.56586667,  0.02071689],
        [-1.61352584,  1.15923688]],

       [[ 0.70520555,  0.44244506],
        [ 0.21768908,  0.72877471]],

       [[-0.8389816 ,  0.8580978 ],
        [-1.63359674,  1.42648438]],

       [[ 0.39760756,  0.40111782],
        [ 0.85713425, -1.20106059]]])

In [61]:
a4.reshape(2,-1)

array([[ 0.56586667,  0.02071689, -1.61352584,  1.15923688,  0.70520555,
         0.44244506,  0.21768908,  0.72877471],
       [-0.8389816 ,  0.8580978 , -1.63359674,  1.42648438,  0.39760756,
         0.40111782,  0.85713425, -1.20106059]])

In [65]:
a4.reshape(2,4,2)

array([[[ 0.56586667,  0.02071689],
        [-1.61352584,  1.15923688],
        [ 0.70520555,  0.44244506],
        [ 0.21768908,  0.72877471]],

       [[-0.8389816 ,  0.8580978 ],
        [-1.63359674,  1.42648438],
        [ 0.39760756,  0.40111782],
        [ 0.85713425, -1.20106059]]])

In [66]:
a1

array(['4', '5', '6', '7', 'Harsh', '34.23', 'True'], dtype='<U11')

In [70]:
a1[::-1]

array(['True', '34.23', 'Harsh', '7', '6', '5', '4'], dtype='<U11')

In [72]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
a2[0]

array([1, 2, 3])

In [77]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [78]:
a5 = np.random.randint(2,90,(6,5))

In [82]:
a5

array([[ 9, 89, 75, 26, 87],
       [83, 31, 43, 81, 15],
       [49, 50, 73, 48, 59],
       [ 9,  9, 40, 34, 76],
       [80, 61, 15, 62, 37],
       [32, 88, 31, 82, 15]])

In [81]:
a5[0,1] = 89

In [87]:
a6 = np.random.randint(0,3,(3,3))

In [88]:
a6

array([[2, 2, 1],
       [2, 0, 0],
       [2, 1, 1]])

In [89]:
a7 = np.random.randint(0,3,(3,3))

In [90]:
a7

array([[2, 1, 0],
       [1, 0, 1],
       [2, 0, 1]])

In [91]:
a6*a7

array([[4, 2, 0],
       [2, 0, 0],
       [4, 0, 1]])

In [93]:
a6@a7

array([[8, 2, 3],
       [4, 2, 0],
       [7, 2, 2]])

In [94]:
a6+100

array([[102, 102, 101],
       [102, 100, 100],
       [102, 101, 101]])

In [95]:
a6+3

array([[5, 5, 4],
       [5, 3, 3],
       [5, 4, 4]])

In [96]:
a6/0

<ipython-input-96-fb79fded0e91>:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
<ipython-input-96-fb79fded0e91>:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, inf],
       [inf, nan, nan],
       [inf, inf, inf]])

In [98]:
a6**3

array([[8, 8, 1],
       [8, 0, 0],
       [8, 1, 1]], dtype=int32)

In [100]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
a6

array([[2, 2, 1],
       [2, 0, 0],
       [2, 1, 1]])

In [104]:
a7 = np.ones((4,3))  
a7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [108]:
a6

array([[2, 2, 1],
       [2, 0, 0],
       [2, 1, 1]])

In [109]:
a6.T

array([[2, 2, 2],
       [2, 0, 1],
       [1, 0, 1]])

In [110]:
np.sqrt(a6)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 0.        , 0.        ],
       [1.41421356, 1.        , 1.        ]])

In [111]:
np.exp(a6)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 1.        , 1.        ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [112]:
np.log10(a6)

<ipython-input-112-e9f34b29d53b>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a6)


array([[0.30103, 0.30103, 0.     ],
       [0.30103,    -inf,    -inf],
       [0.30103, 0.     , 0.     ]])

In [119]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [126]:
np.arange(1.8,10.9,1.5)

array([ 1.8,  3.3,  4.8,  6.3,  7.8,  9.3, 10.8])

In [128]:
np.linspace(2,3,num = 60,retstep = True)

(array([2.        , 2.01694915, 2.03389831, 2.05084746, 2.06779661,
        2.08474576, 2.10169492, 2.11864407, 2.13559322, 2.15254237,
        2.16949153, 2.18644068, 2.20338983, 2.22033898, 2.23728814,
        2.25423729, 2.27118644, 2.28813559, 2.30508475, 2.3220339 ,
        2.33898305, 2.3559322 , 2.37288136, 2.38983051, 2.40677966,
        2.42372881, 2.44067797, 2.45762712, 2.47457627, 2.49152542,
        2.50847458, 2.52542373, 2.54237288, 2.55932203, 2.57627119,
        2.59322034, 2.61016949, 2.62711864, 2.6440678 , 2.66101695,
        2.6779661 , 2.69491525, 2.71186441, 2.72881356, 2.74576271,
        2.76271186, 2.77966102, 2.79661017, 2.81355932, 2.83050847,
        2.84745763, 2.86440678, 2.88135593, 2.89830508, 2.91525424,
        2.93220339, 2.94915254, 2.96610169, 2.98305085, 3.        ]),
 0.01694915254237288)

In [131]:
np.logspace(2,4,num= 10,base = 9)

array([  81.        ,  131.989356  ,  215.07642095,  350.46664558,
        571.08477593,  930.58162711, 1516.381107  , 2470.94031807,
       4026.3928555 , 6561.        ])

In [132]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [2]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
cf.go_offline()

In [7]:
df = pd.DataFrame(np.random.randn(100,3), columns =['A','B','C'])

In [8]:
df

A         B         C
0  -0.261084  0.957115 -1.256694
1   0.274963  0.546303  0.838473
2   1.526529  0.999060 -1.451191
3  -0.771542  0.853606  0.464884
4  -0.575099 -1.239406  1.661086
..       ...       ...       ...
95  0.201186 -0.512197 -0.931516
96 -0.259130  0.810883  0.293307
97  0.414118  1.638332  0.294124
98  1.034018  0.226833  0.286010
99  0.320533  0.979245 -1.629572

[100 rows x 3 columns]

In [9]:
df.iplot()

In [11]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [12]:
df1.iplot()

In [13]:
df1

0
0   52
1   61
2   42
3   36
4   30
..  ..
95  44
96  43
97  99
98  13
99  88

[100 rows x 1 columns]

In [15]:
df.iplot(x='A',y = 'B',mode = 'markers')

In [17]:
df2 = sns.load_dataset('titanic')

In [18]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [25]:
df2.iplot(x='age',y= 'pclass',mode='markers')

In [30]:
df2.iplot(x='fare',y= 'pclass',mode='markers')

In [27]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [28]:
df2.iplot(kind = 'bar',x = 'sex',y='survived')