In [3]:
import pandas as pd

In [4]:
data = {
    'name' : ['Harsh','Kiran','Sunil','Tulika'],
    'salary' : [100, 200,300, 400 ],
    'mail_id' : ['harshinde@gmail.com', 'kiran@gmail.com', 'suniol@gmail.com', 'tulika@gmail.com'],
    'add' : ['nashik','nashik','nashik','pune']
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

name  salary              mail_id     add
0   Harsh     100  harshinde@gmail.com  nashik
1   Kiran     200      kiran@gmail.com  nashik
2   Sunil     300     suniol@gmail.com  nashik
3  Tulika     400     tulika@gmail.com    pune

In [7]:
df.loc['a':'c']

Empty DataFrame
Columns: [name, salary, mail_id, add]
Index: []

In [8]:
df.iloc[1:3]

name  salary           mail_id     add
1  Kiran     200   kiran@gmail.com  nashik
2  Sunil     300  suniol@gmail.com  nashik

In [9]:
data2 = {
    'pf_number' : [1332,4345,6575,2556],
    'income_tax' : [443,321,657,432],
    'mobile_no' : [314444253,334566565,342323545,64534423],
    'courses' : ['ds','BD','ai','Blkchain']
}

In [10]:
df2 = pd.DataFrame(data2)

In [11]:
df

name  salary              mail_id     add
0   Harsh     100  harshinde@gmail.com  nashik
1   Kiran     200      kiran@gmail.com  nashik
2   Sunil     300     suniol@gmail.com  nashik
3  Tulika     400     tulika@gmail.com    pune

In [12]:
df2

pf_number  income_tax  mobile_no   courses
0       1332         443  314444253        ds
1       4345         321  334566565        BD
2       6575         657  342323545        ai
3       2556         432   64534423  Blkchain

In [13]:
pd.concat([df,df2])

name  salary              mail_id     add  pf_number  income_tax  \
0   Harsh   100.0  harshinde@gmail.com  nashik        NaN         NaN   
1   Kiran   200.0      kiran@gmail.com  nashik        NaN         NaN   
2   Sunil   300.0     suniol@gmail.com  nashik        NaN         NaN   
3  Tulika   400.0     tulika@gmail.com    pune        NaN         NaN   
0     NaN     NaN                  NaN     NaN     1332.0       443.0   
1     NaN     NaN                  NaN     NaN     4345.0       321.0   
2     NaN     NaN                  NaN     NaN     6575.0       657.0   
3     NaN     NaN                  NaN     NaN     2556.0       432.0   

     mobile_no   courses  
0          NaN       NaN  
1          NaN       NaN  
2          NaN       NaN  
3          NaN       NaN  
0  314444253.0        ds  
1  334566565.0        BD  
2  342323545.0        ai  
3   64534423.0  Blkchain

In [14]:
datax = {
    '0' : ['Harsh','Kiran','Sunil','Tulika'],
    '1' : [100, 200,300, 400 ],
    '2' : ['harshinde@gmail.com', 'kiran@gmail.com', 'suniol@gmail.com', 'tulika@gmail.com'],
    '3' : ['nashik','nashik','nashik','pune']
}

In [15]:
datay = {
    '0' : [1332,4345,6575,2556],
    '1' : [443,321,657,432],
    '2' : [314444253,334566565,342323545,64534423],
    '3' : ['ds','BD','ai','Blkchain']
}

In [16]:
dfx = pd.DataFrame(datax)
dfy = pd.DataFrame(datay)

In [17]:
pd.concat([dfx,dfy])

0    1                    2         3
0   Harsh  100  harshinde@gmail.com    nashik
1   Kiran  200      kiran@gmail.com    nashik
2   Sunil  300     suniol@gmail.com    nashik
3  Tulika  400     tulika@gmail.com      pune
0    1332  443            314444253        ds
1    4345  321            334566565        BD
2    6575  657            342323545        ai
3    2556  432             64534423  Blkchain

In [18]:
data3 = {
    'emp_id' : [101,102,103,104],
    'salary' :[543,234,654,868],
    'pf' : [12,43,65,23]
}

In [19]:
data4 = {
    'emp_id' : [101,102,103,105],
    'mob_no' : [3434,1341,5345,6543],
    'house_num' : [1,2,3,4 ]
}

In [20]:
df3 = pd.DataFrame(data3)

In [21]:
df4 = pd.DataFrame(data4)

In [22]:
df3

emp_id  salary  pf
0     101     543  12
1     102     234  43
2     103     654  65
3     104     868  23

In [23]:
df4

emp_id  mob_no  house_num
0     101    3434          1
1     102    1341          2
2     103    5345          3
3     105    6543          4

In [24]:
pd.merge(df3,df4)

emp_id  salary  pf  mob_no  house_num
0     101     543  12    3434          1
1     102     234  43    1341          2
2     103     654  65    5345          3

In [25]:
pd.merge(df3,df4 ,  how = 'left')

emp_id  salary  pf  mob_no  house_num
0     101     543  12  3434.0        1.0
1     102     234  43  1341.0        2.0
2     103     654  65  5345.0        3.0
3     104     868  23     NaN        NaN

In [26]:
pd.merge(df3,df4 ,  how = 'right')

emp_id  salary    pf  mob_no  house_num
0     101   543.0  12.0    3434          1
1     102   234.0  43.0    1341          2
2     103   654.0  65.0    5345          3
3     105     NaN   NaN    6543          4

In [27]:
pd.merge(df3,df4 , how = 'left', on = 'emp_id')

emp_id  salary  pf  mob_no  house_num
0     101     543  12  3434.0        1.0
1     102     234  43  1341.0        2.0
2     103     654  65  5345.0        3.0
3     104     868  23     NaN        NaN

In [26]:
data5 = {
    'emp_id1' : [101,102,103,104],
    'salary' :[543,234,654,868],
    'pf' : [12,43,65,23]
}

data6 = {
    'emp_id2' : [101,102,103,105],
    'mob_no' : [3434,1341,5345,6543],
    'house_num' : [1,2,3,4 ]
}

In [27]:
df5 = pd.DataFrame(data5)
df6 = pd.DataFrame(data6)

In [28]:
df7 = pd.merge(df5,df6, left_on = 'emp_id1', right_on = 'emp_id2')
df7

emp_id1  salary  pf  emp_id2  mob_no  house_num
0      101     543  12      101    3434          1
1      102     234  43      102    1341          2
2      103     654  65      103    5345          3

In [29]:
data7 = {
    'emp_id' : [101,102,103,104],
    'salary' : [543,234,654,868],
    'pf' : [12,43,65,23]
}

data8 = {
    'emp_id' : [101,102,103,105],
    'salary' : [543,234,654,868],
    'house_num' : [1,2,3,4]
}

In [30]:
df7 = pd.DataFrame(data7)
df8 = pd.DataFrame(data8)

In [31]:
df7

emp_id  salary  pf
0     101     543  12
1     102     234  43
2     103     654  65
3     104     868  23

In [32]:
df8

emp_id  salary  house_num
0     101     543          1
1     102     234          2
2     103     654          3
3     105     868          4

In [33]:
pd.merge(df7,df8, on = ['emp_id','salary'])

emp_id  salary  pf  house_num
0     101     543  12          1
1     102     234  43          2
2     103     654  65          3

In [34]:
data9 = {
    'emp_id1' : [101,102,103,104],
    'salary1' : [543,234,654,868],
    'pf' : [12,43,65,23]
}

data10 = {
    'emp_id2' : [101,102,103,105,106],
    'salary2' : [543,234,654,868,432],
    'house_num' : [1,2,3,4,5 ]
}

In [35]:
df9 = pd.DataFrame(data9, index= ['a','b','c','d'])
df10 = pd.DataFrame(data10, index = ['a','b','d','e','f'])

In [36]:
df9

emp_id1  salary1  pf
a      101      543  12
b      102      234  43
c      103      654  65
d      104      868  23

In [37]:
df10

emp_id2  salary2  house_num
a      101      543          1
b      102      234          2
d      103      654          3
e      105      868          4
f      106      432          5

In [38]:
df9.join(df10)

emp_id1  salary1  pf  emp_id2  salary2  house_num
a      101      543  12    101.0    543.0        1.0
b      102      234  43    102.0    234.0        2.0
c      103      654  65      NaN      NaN        NaN
d      104      868  23    103.0    654.0        3.0

In [39]:
sales_data = pd.read_csv(r"C:\Users\harsh\Downloads\sales_data_final.csv")

In [41]:
sales_data.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [42]:
def profit_flag(a ):
    if a>0:
        return 'Positive'
    else:
        return 'Negative'

In [43]:
 sales_data['flag_profit'] = sales_data['profit'].apply(profit_flag)

In [78]:
sales_data.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     Positive   
1      0.1   36.036          9.72         Medium  2011     Positive   
2      0.0   29.640          8.17           High  2011     Positive   
3      0.5  -26.055          4.82           High  2011     Negative   
4      0.1   37.770          4.70         Medium  2011     Positive   

   len_cust_name  flag_quantity sq_quantity  
0             15            Low           4  
1             11            Low           9  
2             13            Low          16  
3             12            Low           9  
4             11           High          25  

[5 rows x 25 columns]

In [45]:
sales_data['len_cust_name'] = sales_data['customer_name'].apply(len)

In [46]:
#sales_data['len_name'] = sales_data['customer_name'].apply(len)

In [50]:
#sales_data.drop('len_name',axis = 1,inplace = True)

In [73]:
def quant(a):
    if a>5 and a<10:
        return 'Medium'
    elif a < 5:
        return 'Low'
    else:
        return 'High'

In [74]:
sales_data['flag_quantity'] = sales_data['quantity'].apply(quant)

In [71]:
sales_data['sq_quantity'] = sales_data['quantity'].apply(lambda a:a**2)

# NUMPY

In [81]:
import numpy as np

In [83]:
p = np.array([2,3,5,6,7,4])

In [84]:
type(p)

numpy.ndarray

In [85]:
p

array([2, 3, 5, 6, 7, 4])

In [90]:
np.array([[1,2,3],[5,6,7]])

array([[1, 2, 3],
       [5, 6, 7]])

In [91]:
np.array([[2,3,4,5],[9,6,7,8]])

array([[2, 3, 4, 5],
       [9, 6, 7, 8]])

In [92]:
l = [[2,3,4,5],[9,6,7,8]]

In [93]:
l[0][0]

2

In [95]:
a = np.array([3,5,7,8] , ndmin= 5)

In [96]:
a

array([[[[[3, 5, 7, 8]]]]])

In [97]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [98]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
arr.ndim

2

In [103]:
np.random.randint(1,10,(4,4))

array([[8, 4, 4, 3],
       [8, 8, 7, 5],
       [2, 5, 1, 9],
       [7, 6, 3, 6]])

In [104]:
np.random.randint(1,10,(4,4,2))

array([[[2, 4],
        [1, 3],
        [8, 3],
        [6, 1]],

       [[3, 1],
        [2, 2],
        [5, 5],
        [1, 1]],

       [[1, 3],
        [7, 8],
        [8, 1],
        [8, 5]],

       [[8, 1],
        [9, 6],
        [8, 5],
        [2, 6]]])